#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ENV_FILE="$SCRIPT_DIR/.env"

trim() {
  local value="$1"
  value="${value#${value%%[![:space:]]*}}"
  value="${value%${value##*[![:space:]]}}"
  printf '%s' "$value"
}

load_existing_env() {
  local source_file="$1"
  [[ -f "$source_file" ]] || return 0

  while IFS= read -r line || [[ -n "$line" ]]; do
    line=$(trim "$line")
    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue
    [[ "$line" != *=* ]] && continue

    local key="${line%%=*}"
    local value="${line#*=}"

    key=$(trim "$key")
    value=$(trim "$value")

    if [[ "$value" == '"'*'"' ]] || [[ "$value" == "'"*"'" ]]; then
      value="${value:1:${#value}-2}"
    fi

    printf -v "$key" '%s' "$value"
  done < "$source_file"
}

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local secret="${4:-false}"
  local value

  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$prompt_text [$default_value]: " value || true
    printf '\n'
  else
    read -r -p "$prompt_text [$default_value]: " value || true
  fi

  if [[ -z "$value" ]]; then
    value="$default_value"
  fi

  printf -v "$var_name" '%s' "$value"
}

prompt_choice() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  shift 3
  local allowed=("$@")
  local value

  while true; do
    read -r -p "$prompt_text [$default_value]: " value || true
    if [[ -z "$value" ]]; then
      value="$default_value"
    fi

    local option
    for option in "${allowed[@]}"; do
      if [[ "$value" == "$option" ]]; then
        printf -v "$var_name" '%s' "$value"
        return 0
      fi
    done

    printf 'Invalid value. Allowed: %s\n' "${allowed[*]}"
  done
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return 0
  fi

  python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# =============================================================================
# Shopanda — Generated by install.sh
# =============================================================================
# Review these values before using them in production.

# === Server ===
SHOPANDA_SERVER_HOST="$SHOPANDA_SERVER_HOST"
SHOPANDA_SERVER_PORT="$SHOPANDA_SERVER_PORT"
SHOPANDA_SERVER_PUBLIC_BASE_URL="$SHOPANDA_SERVER_PUBLIC_BASE_URL"

# === Database (PostgreSQL) ===
DATABASE_URL="$DATABASE_URL"
SHOPANDA_DATABASE_HOST="$SHOPANDA_DATABASE_HOST"
SHOPANDA_DATABASE_PORT="$SHOPANDA_DATABASE_PORT"
SHOPANDA_DATABASE_USER="$SHOPANDA_DATABASE_USER"
SHOPANDA_DATABASE_PASSWORD="$SHOPANDA_DATABASE_PASSWORD"
SHOPANDA_DATABASE_NAME="$SHOPANDA_DATABASE_NAME"
SHOPANDA_DATABASE_SSLMODE="$SHOPANDA_DATABASE_SSLMODE"

# === Logging ===
SHOPANDA_LOG_LEVEL="$SHOPANDA_LOG_LEVEL"
SHOPANDA_LOG_FORMAT="$SHOPANDA_LOG_FORMAT"

# === Authentication ===
SHOPANDA_AUTH_JWT_SECRET="$SHOPANDA_AUTH_JWT_SECRET"
SHOPANDA_AUTH_JWT_TTL="$SHOPANDA_AUTH_JWT_TTL"

# === Mail (SMTP) ===
SHOPANDA_MAIL_DRIVER="$SHOPANDA_MAIL_DRIVER"
SHOPANDA_MAIL_SMTP_HOST="$SHOPANDA_MAIL_SMTP_HOST"
SHOPANDA_MAIL_SMTP_PORT="$SHOPANDA_MAIL_SMTP_PORT"
SHOPANDA_MAIL_SMTP_USER="$SHOPANDA_MAIL_SMTP_USER"
SHOPANDA_MAIL_SMTP_PASSWORD="$SHOPANDA_MAIL_SMTP_PASSWORD"
SHOPANDA_MAIL_SMTP_FROM="$SHOPANDA_MAIL_SMTP_FROM"

# === Media Storage ===
SHOPANDA_MEDIA_STORAGE="$SHOPANDA_MEDIA_STORAGE"
SHOPANDA_MEDIA_LOCAL_BASE_PATH="$SHOPANDA_MEDIA_LOCAL_BASE_PATH"
SHOPANDA_MEDIA_LOCAL_BASE_URL="$SHOPANDA_MEDIA_LOCAL_BASE_URL"

# === Cache ===
SHOPANDA_CACHE_DRIVER="$SHOPANDA_CACHE_DRIVER"

# === Frontend ===
SHOPANDA_FRONTEND_ENABLED="$SHOPANDA_FRONTEND_ENABLED"
SHOPANDA_FRONTEND_MODE="$SHOPANDA_FRONTEND_MODE"
SHOPANDA_FRONTEND_THEME_PATH="$SHOPANDA_FRONTEND_THEME_PATH"

# === CDN ===
SHOPANDA_CDN_BASE_URL="$SHOPANDA_CDN_BASE_URL"

# === Webhooks ===
SHOPANDA_WEBHOOKS_SECRET_STRIPE="$SHOPANDA_WEBHOOKS_SECRET_STRIPE"
SHOPANDA_WEBHOOKS_SECRET_PAYPAL="$SHOPANDA_WEBHOOKS_SECRET_PAYPAL"

# === Rate Limiting ===
SHOPANDA_RATE_LIMIT_ENABLED="$SHOPANDA_RATE_LIMIT_ENABLED"
SHOPANDA_RATE_LIMIT_DEFAULT_RATE="$SHOPANDA_RATE_LIMIT_DEFAULT_RATE"
SHOPANDA_RATE_LIMIT_DEFAULT_BURST="$SHOPANDA_RATE_LIMIT_DEFAULT_BURST"

# === Seeding ===
SHOPANDA_SEED_ADMIN_PASSWORD="$SHOPANDA_SEED_ADMIN_PASSWORD"

# === Development ===
SHOPANDA_DEV_MODE="$SHOPANDA_DEV_MODE"

# === Testing ===
SHOPANDA_TEST_DSN="$SHOPANDA_TEST_DSN"
EOF
}

printf 'Shopanda interactive installer\n\n'

load_existing_env "$SCRIPT_DIR/.env.example"
load_existing_env "$ENV_FILE"

SHOPANDA_AUTH_JWT_SECRET=${SHOPANDA_AUTH_JWT_SECRET:-$(generate_secret)}
SHOPANDA_SERVER_HOST=${SHOPANDA_SERVER_HOST:-0.0.0.0}
SHOPANDA_SERVER_PORT=${SHOPANDA_SERVER_PORT:-8080}
SHOPANDA_SERVER_PUBLIC_BASE_URL=${SHOPANDA_SERVER_PUBLIC_BASE_URL:-http://localhost:8080}
DATABASE_URL=${DATABASE_URL:-}
SHOPANDA_DATABASE_HOST=${SHOPANDA_DATABASE_HOST:-localhost}
SHOPANDA_DATABASE_PORT=${SHOPANDA_DATABASE_PORT:-5432}
SHOPANDA_DATABASE_USER=${SHOPANDA_DATABASE_USER:-shopanda}
SHOPANDA_DATABASE_PASSWORD=${SHOPANDA_DATABASE_PASSWORD:-changeme}
SHOPANDA_DATABASE_NAME=${SHOPANDA_DATABASE_NAME:-shopanda}
SHOPANDA_DATABASE_SSLMODE=${SHOPANDA_DATABASE_SSLMODE:-disable}
SHOPANDA_LOG_LEVEL=${SHOPANDA_LOG_LEVEL:-info}
SHOPANDA_LOG_FORMAT=${SHOPANDA_LOG_FORMAT:-json}
SHOPANDA_AUTH_JWT_TTL=${SHOPANDA_AUTH_JWT_TTL:-24h}
SHOPANDA_MAIL_DRIVER=${SHOPANDA_MAIL_DRIVER:-smtp}
SHOPANDA_MAIL_SMTP_HOST=${SHOPANDA_MAIL_SMTP_HOST:-localhost}
SHOPANDA_MAIL_SMTP_PORT=${SHOPANDA_MAIL_SMTP_PORT:-587}
SHOPANDA_MAIL_SMTP_USER=${SHOPANDA_MAIL_SMTP_USER:-}
SHOPANDA_MAIL_SMTP_PASSWORD=${SHOPANDA_MAIL_SMTP_PASSWORD:-}
SHOPANDA_MAIL_SMTP_FROM=${SHOPANDA_MAIL_SMTP_FROM:-noreply@example.com}
SHOPANDA_MEDIA_STORAGE=${SHOPANDA_MEDIA_STORAGE:-local}
SHOPANDA_MEDIA_LOCAL_BASE_PATH=${SHOPANDA_MEDIA_LOCAL_BASE_PATH:-./public/media}
SHOPANDA_MEDIA_LOCAL_BASE_URL=${SHOPANDA_MEDIA_LOCAL_BASE_URL:-/media}
SHOPANDA_CACHE_DRIVER=${SHOPANDA_CACHE_DRIVER:-postgres}
SHOPANDA_FRONTEND_ENABLED=${SHOPANDA_FRONTEND_ENABLED:-false}
SHOPANDA_FRONTEND_MODE=${SHOPANDA_FRONTEND_MODE:-ssr}
SHOPANDA_FRONTEND_THEME_PATH=${SHOPANDA_FRONTEND_THEME_PATH:-themes/default}
SHOPANDA_CDN_BASE_URL=${SHOPANDA_CDN_BASE_URL:-}
SHOPANDA_WEBHOOKS_SECRET_STRIPE=${SHOPANDA_WEBHOOKS_SECRET_STRIPE:-}
SHOPANDA_WEBHOOKS_SECRET_PAYPAL=${SHOPANDA_WEBHOOKS_SECRET_PAYPAL:-}
SHOPANDA_RATE_LIMIT_ENABLED=${SHOPANDA_RATE_LIMIT_ENABLED:-false}
SHOPANDA_RATE_LIMIT_DEFAULT_RATE=${SHOPANDA_RATE_LIMIT_DEFAULT_RATE:-10}
SHOPANDA_RATE_LIMIT_DEFAULT_BURST=${SHOPANDA_RATE_LIMIT_DEFAULT_BURST:-20}
SHOPANDA_SEED_ADMIN_PASSWORD=${SHOPANDA_SEED_ADMIN_PASSWORD:-changeme}
SHOPANDA_DEV_MODE=${SHOPANDA_DEV_MODE:-}
SHOPANDA_TEST_DSN=${SHOPANDA_TEST_DSN:-}

printf 'Server configuration\n'
prompt_value SHOPANDA_SERVER_HOST 'Bind host' "$SHOPANDA_SERVER_HOST"
prompt_value SHOPANDA_SERVER_PORT 'Bind port' "$SHOPANDA_SERVER_PORT"
prompt_value SHOPANDA_SERVER_PUBLIC_BASE_URL 'Public base URL' "$SHOPANDA_SERVER_PUBLIC_BASE_URL"

printf '\nDatabase configuration\n'
prompt_value DATABASE_URL 'Full DATABASE_URL (leave empty to use individual fields)' "$DATABASE_URL"
if [[ -z "$DATABASE_URL" ]]; then
  prompt_value SHOPANDA_DATABASE_HOST 'Database host' "$SHOPANDA_DATABASE_HOST"
  prompt_value SHOPANDA_DATABASE_PORT 'Database port' "$SHOPANDA_DATABASE_PORT"
  prompt_value SHOPANDA_DATABASE_USER 'Database user' "$SHOPANDA_DATABASE_USER"
  prompt_value SHOPANDA_DATABASE_PASSWORD 'Database password' "$SHOPANDA_DATABASE_PASSWORD" true
  prompt_value SHOPANDA_DATABASE_NAME 'Database name' "$SHOPANDA_DATABASE_NAME"
  prompt_choice SHOPANDA_DATABASE_SSLMODE 'Database sslmode' "$SHOPANDA_DATABASE_SSLMODE" disable require verify-ca verify-full
else
  SHOPANDA_DATABASE_HOST=${SHOPANDA_DATABASE_HOST:-localhost}
  SHOPANDA_DATABASE_PORT=${SHOPANDA_DATABASE_PORT:-5432}
  SHOPANDA_DATABASE_USER=${SHOPANDA_DATABASE_USER:-shopanda}
  SHOPANDA_DATABASE_PASSWORD=${SHOPANDA_DATABASE_PASSWORD:-changeme}
  SHOPANDA_DATABASE_NAME=${SHOPANDA_DATABASE_NAME:-shopanda}
  SHOPANDA_DATABASE_SSLMODE=${SHOPANDA_DATABASE_SSLMODE:-disable}
fi

printf '\nAuthentication and logging\n'
prompt_value SHOPANDA_AUTH_JWT_SECRET 'JWT secret' "$SHOPANDA_AUTH_JWT_SECRET" true
prompt_value SHOPANDA_AUTH_JWT_TTL 'JWT TTL' "$SHOPANDA_AUTH_JWT_TTL"
prompt_choice SHOPANDA_LOG_LEVEL 'Log level' "$SHOPANDA_LOG_LEVEL" debug info warn error
prompt_choice SHOPANDA_LOG_FORMAT 'Log format' "$SHOPANDA_LOG_FORMAT" json text

printf '\nMail configuration\n'
prompt_choice SHOPANDA_MAIL_DRIVER 'Mail driver' "$SHOPANDA_MAIL_DRIVER" smtp
prompt_value SHOPANDA_MAIL_SMTP_HOST 'SMTP host' "$SHOPANDA_MAIL_SMTP_HOST"
prompt_value SHOPANDA_MAIL_SMTP_PORT 'SMTP port' "$SHOPANDA_MAIL_SMTP_PORT"
prompt_value SHOPANDA_MAIL_SMTP_USER 'SMTP user' "$SHOPANDA_MAIL_SMTP_USER"
prompt_value SHOPANDA_MAIL_SMTP_PASSWORD 'SMTP password' "$SHOPANDA_MAIL_SMTP_PASSWORD" true
prompt_value SHOPANDA_MAIL_SMTP_FROM 'SMTP from address' "$SHOPANDA_MAIL_SMTP_FROM"

printf '\nMedia, cache, and frontend\n'
prompt_choice SHOPANDA_MEDIA_STORAGE 'Media storage driver' "$SHOPANDA_MEDIA_STORAGE" local
prompt_value SHOPANDA_MEDIA_LOCAL_BASE_PATH 'Local media path' "$SHOPANDA_MEDIA_LOCAL_BASE_PATH"
prompt_value SHOPANDA_MEDIA_LOCAL_BASE_URL 'Local media base URL' "$SHOPANDA_MEDIA_LOCAL_BASE_URL"
prompt_choice SHOPANDA_CACHE_DRIVER 'Cache driver' "$SHOPANDA_CACHE_DRIVER" postgres
prompt_choice SHOPANDA_FRONTEND_ENABLED 'Enable SSR storefront (true/false)' "$SHOPANDA_FRONTEND_ENABLED" true false
prompt_choice SHOPANDA_FRONTEND_MODE 'Frontend mode' "$SHOPANDA_FRONTEND_MODE" ssr
prompt_value SHOPANDA_FRONTEND_THEME_PATH 'Frontend theme path' "$SHOPANDA_FRONTEND_THEME_PATH"
prompt_value SHOPANDA_CDN_BASE_URL 'CDN base URL (optional)' "$SHOPANDA_CDN_BASE_URL"

printf '\nWebhooks and rate limiting\n'
prompt_value SHOPANDA_WEBHOOKS_SECRET_STRIPE 'Stripe webhook secret (optional)' "$SHOPANDA_WEBHOOKS_SECRET_STRIPE" true
prompt_value SHOPANDA_WEBHOOKS_SECRET_PAYPAL 'PayPal webhook secret (optional)' "$SHOPANDA_WEBHOOKS_SECRET_PAYPAL" true
prompt_choice SHOPANDA_RATE_LIMIT_ENABLED 'Enable rate limiting (true/false)' "$SHOPANDA_RATE_LIMIT_ENABLED" true false
prompt_value SHOPANDA_RATE_LIMIT_DEFAULT_RATE 'Rate limit default rate' "$SHOPANDA_RATE_LIMIT_DEFAULT_RATE"
prompt_value SHOPANDA_RATE_LIMIT_DEFAULT_BURST 'Rate limit default burst' "$SHOPANDA_RATE_LIMIT_DEFAULT_BURST"

printf '\nOptional seeding and development settings\n'
prompt_value SHOPANDA_SEED_ADMIN_PASSWORD 'Seed admin password' "$SHOPANDA_SEED_ADMIN_PASSWORD" true
prompt_value SHOPANDA_DEV_MODE 'Development mode flag (optional)' "$SHOPANDA_DEV_MODE"
prompt_value SHOPANDA_TEST_DSN 'Test DSN (optional)' "$SHOPANDA_TEST_DSN"

write_env_file

printf '\nWrote %s\n' "$ENV_FILE"
printf 'Next steps:\n'
printf '  1. Review .env\n'
printf '  2. Run ./shopanda setup or ./app setup depending on your binary name\n'
printf '  3. Start the server with ./shopanda serve or ./app serve\n'