package catalog

import (
	"errors"
	"strings"
	"time"
)

// Category represents a hierarchical navigation node in the catalog.
type Category struct {
	ID       string
	ParentID *string
	Name     string
	Slug     string
	Position int
	Meta     map[string]interface{}

	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewCategory creates a category with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewCategory(id, name, slug string) (Category, error) {
	id = strings.TrimSpace(id)
	name = strings.TrimSpace(name)
	slug = strings.TrimSpace(slug)
	if id == "" {
		return Category{}, errors.New("category id must not be empty")
	}
	if name == "" {
		return Category{}, errors.New("category name must not be empty")
	}
	if slug == "" {
		return Category{}, errors.New("category slug must not be empty")
	}
	now := time.Now().UTC()
	return Category{
		ID:        id,
		Name:      name,
		Slug:      slug,
		Position:  0,
		Meta:      make(map[string]interface{}),
		CreatedAt: now,
		UpdatedAt: now,
	}, nil
}

// NewCategoryFromDB reconstructs a Category from persistent storage.
// No validation is applied; the database is the source of truth.
func NewCategoryFromDB(
	id string,
	parentID *string,
	name, slug string,
	position int,
	meta map[string]interface{},
	createdAt, updatedAt time.Time,
) *Category {
	if meta == nil {
		meta = make(map[string]interface{})
	}
	return &Category{
		ID:        id,
		ParentID:  parentID,
		Name:      name,
		Slug:      slug,
		Position:  position,
		Meta:      meta,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// IsRoot returns true when the category has no parent.
func (c *Category) IsRoot() bool {
	return c.ParentID == nil
}
