package catalog

import (
	"errors"
	"strings"
	"time"
)

// CollectionType represents the kind of collection.
type CollectionType string

const (
	CollectionManual  CollectionType = "manual"
	CollectionDynamic CollectionType = "dynamic"
)

// IsValid returns true if t is a recognised collection type.
func (t CollectionType) IsValid() bool {
	switch t {
	case CollectionManual, CollectionDynamic:
		return true
	}
	return false
}

// Collection represents a curated or rule-based product grouping.
type Collection struct {
	ID   string
	Name string
	Slug string
	Type CollectionType

	Rules map[string]interface{}
	Meta  map[string]interface{}

	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewCollection creates a collection with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewCollection(id, name, slug string, collType CollectionType) (Collection, error) {
	id = strings.TrimSpace(id)
	name = strings.TrimSpace(name)
	slug = strings.TrimSpace(slug)
	if id == "" {
		return Collection{}, errors.New("collection id must not be empty")
	}
	if name == "" {
		return Collection{}, errors.New("collection name must not be empty")
	}
	if slug == "" {
		return Collection{}, errors.New("collection slug must not be empty")
	}
	if !collType.IsValid() {
		return Collection{}, errors.New("collection type must be manual or dynamic")
	}
	now := time.Now().UTC()
	return Collection{
		ID:        id,
		Name:      name,
		Slug:      slug,
		Type:      collType,
		Rules:     make(map[string]interface{}),
		Meta:      make(map[string]interface{}),
		CreatedAt: now,
		UpdatedAt: now,
	}, nil
}

// NewCollectionFromDB reconstructs a Collection from persistent storage.
// No validation is applied; the database is the source of truth.
func NewCollectionFromDB(
	id, name, slug string,
	collType CollectionType,
	rules, meta map[string]interface{},
	createdAt, updatedAt time.Time,
) *Collection {
	if rules == nil {
		rules = make(map[string]interface{})
	}
	if meta == nil {
		meta = make(map[string]interface{})
	}
	return &Collection{
		ID:        id,
		Name:      name,
		Slug:      slug,
		Type:      collType,
		Rules:     rules,
		Meta:      meta,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// IsManual returns true when the collection uses explicit product assignment.
func (c *Collection) IsManual() bool {
	return c.Type == CollectionManual
}

// IsDynamic returns true when the collection uses rule-based product selection.
func (c *Collection) IsDynamic() bool {
	return c.Type == CollectionDynamic
}
