package catalog

import (
	"errors"
	"fmt"
	"time"
)

// Status represents the lifecycle state of a product.
type Status string

const (
	StatusDraft    Status = "draft"
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
)

// IsValid returns true if s is a recognised product status.
func (s Status) IsValid() bool {
	switch s {
	case StatusDraft, StatusActive, StatusArchived:
		return true
	}
	return false
}

// Type is the product taxonomy (simple, virtual, bundle, …).
// It is a typed string for package separation, not compile-time enum
// exhaustiveness — callers must reject unknown values via IsValid /
// Product.Validate (application and persistence layers), matching Status.
// Shipping requirement is derived via RequiresPhysicalShipping (PR-1050);
// other type-specific behavior (composition, downloadable fulfillment, …)
// lands in later Phase 12 PRs.
type Type string

const (
	TypeSimple       Type = "simple"
	TypeVirtual      Type = "virtual"
	TypeBundle       Type = "bundle"
	TypeGrouped      Type = "grouped"
	TypeConfigurable Type = "configurable"
	TypeDownloadable Type = "downloadable"
)

// AllTypes returns every recognised product type in stable order.
// Keep migrations/083_add_products_type.sql CHECK in sync (see product_type_test).
func AllTypes() []Type {
	return []Type{
		TypeSimple,
		TypeVirtual,
		TypeBundle,
		TypeGrouped,
		TypeConfigurable,
		TypeDownloadable,
	}
}

// IsValid returns true if t is a recognised product type.
func (t Type) IsValid() bool {
	for _, allowed := range AllTypes() {
		if t == allowed {
			return true
		}
	}
	return false
}

// RequiresPhysicalShipping reports whether a product of this type needs a
// shipping method at checkout. virtual and downloadable never do; every
// other value (including unknown/empty) does — composites stay true until
// Track C adds child rollup. Unknown/empty defaults to true as a fail-safe.
func (t Type) RequiresPhysicalShipping() bool {
	switch t {
	case TypeVirtual, TypeDownloadable:
		return false
	default:
		return true
	}
}

// AnyRequiresPhysicalShipping is true when at least one type in types needs
// a shipping method. An empty slice returns true (fail closed — nothing was
// resolved yet; callers must not treat "no types" as digital-only).
func AnyRequiresPhysicalShipping(types []Type) bool {
	if len(types) == 0 {
		return true
	}
	for _, t := range types {
		if t.RequiresPhysicalShipping() {
			return true
		}
	}
	return false
}

// Product represents a logical product in the catalog.
type Product struct {
	ID          string
	Name        string
	Slug        string
	Description string
	Status      Status
	Type        Type
	Attributes  map[string]interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewProduct creates a Product with the required fields.
// ID must be generated by the caller (e.g. id.New()).
// Type defaults to TypeSimple (existing catalog behavior).
// Hand-built Product{} literals must set Type (or call Validate) before
// persist — INSERT binds type explicitly and does not rely on the DB DEFAULT.
func NewProduct(id, name, slug string) (Product, error) {
	if id == "" {
		return Product{}, errors.New("product id must not be empty")
	}
	if name == "" {
		return Product{}, errors.New("product name must not be empty")
	}
	if slug == "" {
		return Product{}, errors.New("product slug must not be empty")
	}
	now := time.Now().UTC()
	return Product{
		ID:         id,
		Name:       name,
		Slug:       slug,
		Status:     StatusDraft,
		Type:       TypeSimple,
		Attributes: make(map[string]interface{}),
		CreatedAt:  now,
		UpdatedAt:  now,
	}, nil
}

// RequiresPhysicalShipping reports whether this product needs a shipping
// method at checkout. See Type.RequiresPhysicalShipping.
func (p Product) RequiresPhysicalShipping() bool {
	return p.Type.RequiresPhysicalShipping()
}

// Validate checks fields that must be valid before persist.
// Currently only nil and Type (not Status/Name/Slug — those stay at NewProduct
// / admin request validation). Adapter-agnostic: call from handlers and every
// ProductRepository. When request Type is accepted (PR-1051), set it before Validate.
func (p *Product) Validate() error {
	if p == nil {
		return errors.New("product must not be nil")
	}
	if !p.Type.IsValid() {
		return fmt.Errorf("invalid product type %q", p.Type)
	}
	return nil
}
