package catalog

import (
	"errors"
	"time"
)

// Status represents the lifecycle state of a product.
type Status string

const (
	StatusDraft    Status = "draft"
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
)

// IsValid returns true if s is a recognised product status.
func (s Status) IsValid() bool {
	switch s {
	case StatusDraft, StatusActive, StatusArchived:
		return true
	}
	return false
}

// Product represents a logical product in the catalog.
type Product struct {
	ID          string
	Name        string
	Slug        string
	Description string
	Status      Status
	Attributes  map[string]interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewProduct creates a Product with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewProduct(id, name, slug string) (Product, error) {
	if id == "" {
		return Product{}, errors.New("product id must not be empty")
	}
	if name == "" {
		return Product{}, errors.New("product name must not be empty")
	}
	if slug == "" {
		return Product{}, errors.New("product slug must not be empty")
	}
	now := time.Now().UTC()
	return Product{
		ID:         id,
		Name:       name,
		Slug:       slug,
		Status:     StatusDraft,
		Attributes: make(map[string]interface{}),
		CreatedAt:  now,
		UpdatedAt:  now,
	}, nil
}
