package catalog

import (
	"errors"
	"time"
)

// Variant represents a sellable unit of a product (e.g. size M, color red).
type Variant struct {
	ID         string
	ProductID  string
	SKU        string
	Name       string
	Weight     float64 // kg, 0 = unset
	Attributes map[string]interface{}
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// NewVariant creates a Variant with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewVariant(id, productID, sku string) (Variant, error) {
	if id == "" {
		return Variant{}, errors.New("variant id must not be empty")
	}
	if productID == "" {
		return Variant{}, errors.New("variant product_id must not be empty")
	}
	if sku == "" {
		return Variant{}, errors.New("variant sku must not be empty")
	}
	now := time.Now().UTC()
	return Variant{
		ID:         id,
		ProductID:  productID,
		SKU:        sku,
		Attributes: make(map[string]interface{}),
		CreatedAt:  now,
		UpdatedAt:  now,
	}, nil
}
