package customer

import (
	"errors"
	"time"
)

// Status represents the lifecycle state of a customer account.
type Status string

const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

// IsValid returns true if s is a recognised customer status.
func (s Status) IsValid() bool {
	switch s {
	case StatusActive, StatusDisabled:
		return true
	}
	return false
}

// Role represents the access level of a customer account.
type Role string

const (
	RoleCustomer Role = "customer"
	RoleAdmin    Role = "admin"
	RoleManager  Role = "manager"
	RoleEditor   Role = "editor"
	RoleSupport  Role = "support"
)

// IsValid returns true if r is a recognised customer role.
func (r Role) IsValid() bool {
	switch r {
	case RoleCustomer, RoleAdmin, RoleManager, RoleEditor, RoleSupport:
		return true
	}
	return false
}

// Customer represents a registered customer account.
type Customer struct {
	ID              string
	Email           string
	FirstName       string
	LastName        string
	PasswordHash    string
	TokenGeneration int64
	Role            Role
	Status          Status
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// NewCustomer creates a Customer with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewCustomer(id, email string) (Customer, error) {
	if id == "" {
		return Customer{}, errors.New("customer: id must not be empty")
	}
	if email == "" {
		return Customer{}, errors.New("customer: email must not be empty")
	}
	now := time.Now().UTC()
	return Customer{
		ID:              id,
		Email:           email,
		TokenGeneration: 0,
		Role:            RoleCustomer,
		Status:          StatusActive,
		CreatedAt:       now,
		UpdatedAt:       now,
	}, nil
}

// Disable transitions the customer to disabled status.
func (c *Customer) Disable() error {
	if c.Status != StatusActive {
		return errors.New("customer: only active customers can be disabled")
	}
	c.Status = StatusDisabled
	c.UpdatedAt = time.Now().UTC()
	return nil
}

// Enable transitions the customer to active status.
func (c *Customer) Enable() error {
	if c.Status != StatusDisabled {
		return errors.New("customer: only disabled customers can be enabled")
	}
	c.Status = StatusActive
	c.UpdatedAt = time.Now().UTC()
	return nil
}

// BumpTokenGeneration increments the token generation counter,
// invalidating all previously issued tokens.
func (c *Customer) BumpTokenGeneration() {
	c.TokenGeneration++
	c.UpdatedAt = time.Now().UTC()
}

// SetPassword sets the password hash on the customer.
func (c *Customer) SetPassword(hash string) error {
	if hash == "" {
		return errors.New("customer: password hash must not be empty")
	}
	c.PasswordHash = hash
	c.UpdatedAt = time.Now().UTC()
	return nil
}
