package customer

import (
	"errors"
	"strings"
	"time"
)

// Status represents the lifecycle state of a customer account.
type Status string

const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

// IsValid returns true if s is a recognised customer status.
func (s Status) IsValid() bool {
	switch s {
	case StatusActive, StatusDisabled:
		return true
	}
	return false
}

// Role represents the access level of a customer account.
type Role string

const (
	RoleCustomer Role = "customer"
	RoleAdmin    Role = "admin"
	RoleManager  Role = "manager"
	RoleEditor   Role = "editor"
	RoleSupport  Role = "support"
)

// IsValid returns true if r is a recognised customer role.
func (r Role) IsValid() bool {
	switch r {
	case RoleCustomer, RoleAdmin, RoleManager, RoleEditor, RoleSupport:
		return true
	}
	return false
}

// Customer represents a registered customer account.
type Customer struct {
	ID              string
	Email           string
	FirstName       string
	LastName        string
	PasswordHash    string
	TokenGeneration int64
	EmailVerifiedAt *time.Time
	Role            Role
	Status          Status
	// PendingEmailNonce is the latest issued email-change token nonce. A new
	// change request overwrites it so that previously issued links are rejected.
	// It is cleared once a change is confirmed.
	PendingEmailNonce string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// NewCustomer creates a Customer with the required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewCustomer(id, email string) (Customer, error) {
	if id == "" {
		return Customer{}, errors.New("customer: id must not be empty")
	}
	if email == "" {
		return Customer{}, errors.New("customer: email must not be empty")
	}
	now := time.Now().UTC()
	return Customer{
		ID:              id,
		Email:           email,
		TokenGeneration: 0,
		Role:            RoleCustomer,
		Status:          StatusActive,
		CreatedAt:       now,
		UpdatedAt:       now,
	}, nil
}

// Disable transitions the customer to disabled status.
func (c *Customer) Disable() error {
	if c.Status != StatusActive {
		return errors.New("customer: only active customers can be disabled")
	}
	c.Status = StatusDisabled
	c.UpdatedAt = time.Now().UTC()
	return nil
}

// Enable transitions the customer to active status.
func (c *Customer) Enable() error {
	if c.Status != StatusDisabled {
		return errors.New("customer: only disabled customers can be enabled")
	}
	c.Status = StatusActive
	c.UpdatedAt = time.Now().UTC()
	return nil
}

// BumpTokenGeneration increments the token generation counter,
// invalidating all previously issued tokens.
func (c *Customer) BumpTokenGeneration() {
	c.TokenGeneration++
	c.UpdatedAt = time.Now().UTC()
}

// SetPassword sets the password hash on the customer.
func (c *Customer) SetPassword(hash string) error {
	if hash == "" {
		return errors.New("customer: password hash must not be empty")
	}
	c.PasswordHash = hash
	c.UpdatedAt = time.Now().UTC()
	return nil
}

// MarkEmailVerified records the first successful email verification.
func (c *Customer) MarkEmailVerified() {
	if c.EmailVerifiedAt != nil {
		return
	}
	now := time.Now().UTC()
	c.EmailVerifiedAt = &now
	c.UpdatedAt = now
}

// SetPendingEmailNonce records the latest email-change nonce, invalidating any
// previously issued change links.
func (c *Customer) SetPendingEmailNonce(nonce string) {
	c.PendingEmailNonce = strings.TrimSpace(nonce)
	c.UpdatedAt = time.Now().UTC()
}

// ApplyEmailChange switches the active email to the confirmed new address,
// marks it verified, and clears the pending change nonce.
func (c *Customer) ApplyEmailChange(newEmail string) {
	now := time.Now().UTC()
	c.Email = strings.TrimSpace(newEmail)
	c.EmailVerifiedAt = &now
	c.PendingEmailNonce = ""
	c.UpdatedAt = now
}
