package store

import (
	"errors"
	"strings"
	"time"
)

// Store represents a storefront context with its own currency and locale.
type Store struct {
	ID        string
	Code      string
	Name      string
	Currency  string
	Country   string
	Domain    string
	IsDefault bool

	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewStore creates a Store with required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewStore(id, code, name, currency, country, domain string) (Store, error) {
	id = strings.TrimSpace(id)
	code = strings.TrimSpace(code)
	name = strings.TrimSpace(name)
	currency = strings.TrimSpace(currency)
	country = strings.TrimSpace(country)
	domain = strings.TrimSpace(domain)
	if id == "" {
		return Store{}, errors.New("store id must not be empty")
	}
	if code == "" {
		return Store{}, errors.New("store code must not be empty")
	}
	if name == "" {
		return Store{}, errors.New("store name must not be empty")
	}
	if currency == "" {
		return Store{}, errors.New("store currency must not be empty")
	}
	if len(currency) != 3 {
		return Store{}, errors.New("store currency must be a 3-letter ISO code")
	}
	if country == "" {
		return Store{}, errors.New("store country must not be empty")
	}
	if len(country) != 2 {
		return Store{}, errors.New("store country must be a 2-letter ISO code")
	}
	now := time.Now().UTC()
	return Store{
		ID:        id,
		Code:      code,
		Name:      name,
		Currency:  strings.ToUpper(currency),
		Country:   strings.ToUpper(country),
		Domain:    domain,
		IsDefault: false,
		CreatedAt: now,
		UpdatedAt: now,
	}, nil
}

// NewStoreFromDB reconstructs a Store from persistent storage.
// No validation is applied; the database is the source of truth.
func NewStoreFromDB(
	id, code, name, currency, country, domain string,
	isDefault bool,
	createdAt, updatedAt time.Time,
) *Store {
	return &Store{
		ID:        id,
		Code:      code,
		Name:      name,
		Currency:  currency,
		Country:   country,
		Domain:    domain,
		IsDefault: isDefault,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}
