package store

import (
	"errors"
	"strings"
	"time"
)

// Store represents a storefront context with its own currency and locale.
type Store struct {
	ID        string
	Code      string
	Name      string
	Currency  string
	Country   string
	Language  string
	Domain    string
	IsDefault bool

	CreatedAt time.Time
	UpdatedAt time.Time
}

// NormalizeCurrency trims whitespace, uppercases, and validates a 3-letter ISO currency code.
func NormalizeCurrency(v string) (string, error) {
	v = strings.ToUpper(strings.TrimSpace(v))
	if v == "" {
		return "", errors.New("store currency must not be empty")
	}
	if len(v) != 3 {
		return "", errors.New("store currency must be a 3-letter ISO code")
	}
	return v, nil
}

// NormalizeCountry trims whitespace, uppercases, and validates a 2-letter ISO country code.
func NormalizeCountry(v string) (string, error) {
	v = strings.ToUpper(strings.TrimSpace(v))
	if v == "" {
		return "", errors.New("store country must not be empty")
	}
	if len(v) != 2 {
		return "", errors.New("store country must be a 2-letter ISO code")
	}
	return v, nil
}

// NormalizeLanguage trims whitespace, lowercases, and validates a BCP 47
// language tag (e.g. "en", "de", "pt-BR"). Only the 2- or 5-character forms
// are accepted.
func NormalizeLanguage(v string) (string, error) {
	v = strings.ToLower(strings.TrimSpace(v))
	if v == "" {
		return "", errors.New("store language must not be empty")
	}
	if len(v) != 2 && len(v) != 5 {
		return "", errors.New("store language must be a 2-letter code or 5-character BCP 47 tag (e.g. en, pt-BR)")
	}
	return v, nil
}

// NewStore creates a Store with required fields.
// ID must be generated by the caller (e.g. id.New()).
func NewStore(id, code, name, currency, country, language, domain string) (Store, error) {
	id = strings.TrimSpace(id)
	code = strings.TrimSpace(code)
	name = strings.TrimSpace(name)
	domain = strings.TrimSpace(domain)
	if id == "" {
		return Store{}, errors.New("store id must not be empty")
	}
	if code == "" {
		return Store{}, errors.New("store code must not be empty")
	}
	if name == "" {
		return Store{}, errors.New("store name must not be empty")
	}
	cur, err := NormalizeCurrency(currency)
	if err != nil {
		return Store{}, err
	}
	cty, err := NormalizeCountry(country)
	if err != nil {
		return Store{}, err
	}
	lang, err := NormalizeLanguage(language)
	if err != nil {
		return Store{}, err
	}
	now := time.Now().UTC()
	return Store{
		ID:        id,
		Code:      code,
		Name:      name,
		Currency:  cur,
		Country:   cty,
		Language:  lang,
		Domain:    domain,
		IsDefault: false,
		CreatedAt: now,
		UpdatedAt: now,
	}, nil
}

// NewStoreFromDB reconstructs a Store from persistent storage.
// No validation is applied; the database is the source of truth.
func NewStoreFromDB(
	id, code, name, currency, country, language, domain string,
	isDefault bool,
	createdAt, updatedAt time.Time,
) *Store {
	return &Store{
		ID:        id,
		Code:      code,
		Name:      name,
		Currency:  currency,
		Country:   country,
		Language:  language,
		Domain:    domain,
		IsDefault: isDefault,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}
